# Join market data, Google Trends, and engineered features

This notebook:

1. Loads **technical indicators** from `crypto_prices_with_indicators.csv`
2. Adds **macro + news sentiment** columns from `crypto_prices_macro_sentiment.csv` (merged on `date`)
3. Merges **Google Trends** (`google_trends_clean.csv`) on `date`
4. Builds **ML-ready composite features** (momentum gaps, macro stress, trend z-scores, etc.)
5. Exports `eth_ml_dataset.csv` and `eth_ml_dataset_features.csv` (same table for downstream scripts)

In [57]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 180)

INDICATORS_PATH = "crypto_prices_with_indicators.csv"
MACRO_SENTIMENT_PATH = "crypto_prices_macro_sentiment.csv"
TRENDS_PATH = "google_trends_clean.csv"
OUTPUT_PATH = "eth_ml_dataset.csv"
OUTPUT_FEATURES_PATH = "eth_ml_dataset_features.csv"

In [58]:
def _standardize_date_col(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    if "date" not in out.columns and "Date" in out.columns:
        out = out.rename(columns={"Date": "date"})
    out["date"] = pd.to_datetime(out["date"], errors="coerce")
    return out.dropna(subset=["date"]).sort_values("date").drop_duplicates(subset=["date"], keep="last")


# 1) Technical indicators + base OHLCV-derived columns
prices = pd.read_csv(INDICATORS_PATH)
prices = _standardize_date_col(prices)

# 2) Macro + news sentiment (columns not already in indicators file)
macro = pd.read_csv(MACRO_SENTIMENT_PATH)
macro = _standardize_date_col(macro)
extra_cols = [c for c in macro.columns if c != "date" and c not in prices.columns]
if extra_cols:
    prices = prices.merge(macro[["date"] + extra_cols], on="date", how="left")

# 3) Google Trends
trends = pd.read_csv(TRENDS_PATH)
trends = _standardize_date_col(trends)

print("Prices (+macro) shape:", prices.shape)
print("Trends shape:", trends.shape)
prices.head()

Prices (+macro) shape: (2083, 86)
Trends shape: (3026, 16)

,date,GC=F,VIX,ETH,BTC,eth_ret_1d,eth_ret_3d,eth_ret_7d,eth_sma_10,eth_sma_30,eth_ema_12,eth_ema_26,eth_sma_ratio_10,eth_ema_ratio_12_26,eth_vol_7d,eth_vol_14d,eth_bb_z_20,eth_rsi_14,eth_macd,eth_macd_signal,eth_macd_hist,eth_obv,btc_ret_1d,btc_ret_3d,btc_ret_7d,btc_sma_10,btc_sma_30,btc_ema_12,btc_ema_26,btc_sma_ratio_10,btc_ema_ratio_12_26,btc_vol_7d,btc_vol_14d,btc_bb_z_20,btc_rsi_14,btc_macd,btc_macd_signal,btc_macd_hist,btc_obv,vix_ret_1d,vix_ret_3d,vix_ret_7d,vix_sma_10,vix_sma_30,vix_ema_12,vix_ema_26,vix_sma_ratio_10,vix_ema_ratio_12_26,vix_vol_7d,vix_vol_14d,vix_bb_z_20,vix_rsi_14,vix_macd,vix_macd_signal,vix_macd_hist,vix_obv,gc=f_ret_1d,gc=f_ret_3d,gc=f_ret_7d,gc=f_sma_10,gc=f_sma_30,gc=f_ema_12,gc=f_ema_26,gc=f_sma_ratio_10,gc=f_ema_ratio_12_26,gc=f_vol_7d,gc=f_vol_14d,gc=f_bb_z_20,gc=f_rsi_14,gc=f_macd,gc=f_macd_signal,gc=f_macd_hist,gc=f_obv,btc_eth_spread_1d,eth_news_sent_mean,eth_news_sent_wmean,eth_news_sent_std,eth_news_count,eth_news_pos_ratio,eth_news_neg_ratio,federal_funds_rate,cpi,treasury_10y,fed_rate_change_7d,treasury_10y_change_7d,cpi_yoy_pct
0,2018-01-02,1313.699951,9.77,884.443970,14982.099609,NaN,NaN,NaN,NaN,NaN,884.443970,884.443970,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,14982.099609,14982.099609,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,9.770000,9.770000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,1313.699951,1313.699951,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN
1,2018-01-03,1316.199951,9.15,962.719971,15201.000000,0.088503,NaN,NaN,NaN,NaN,896.486431,890.242192,NaN,0.007014,NaN,NaN,NaN,NaN,6.244239,1.248848,4.995392,5.093160e+09,0.014611,NaN,NaN,NaN,NaN,15015.776593,14998.314453,NaN,0.001164,NaN,NaN,NaN,NaN,17.462139,3.492428,13.969712,1.687190e+10,-0.063460,NaN,NaN,NaN,NaN,9.674616,9.724074,NaN,-0.005086,NaN,NaN,NaN,NaN,-0.049459,-0.009892,-0.039567,0.0,0.001903,NaN,NaN,NaN,NaN,1314.084567,1313.885136,NaN,0.000152,NaN,NaN,NaN,NaN,0.199430,0.039886,0.159544,42.0,-0.073892,0.03173,0.03173,0.0,1.0,0.0,0.0,1.42,247.867,2.44,NaN,NaN,NaN
2,2018-01-04,1319.400024,9.22,980.921997,15599.200195,0.018907,NaN,NaN,NaN,NaN,909.476518,896.959215,NaN,0.013955,NaN,NaN,NaN,NaN,12.517304,3.502539,9.014765,1.159602e+10,0.026196,NaN,NaN,NaN,NaN,15105.534070,15042.824508,NaN,0.004169,NaN,NaN,NaN,NaN,62.709562,15.335855,47.373707,3.865510e+10,0.007650,NaN,NaN,NaN,NaN,9.604675,9.686736,NaN,-0.008471,NaN,NaN,NaN,NaN,-0.082061,-0.024326,-0.057735,0.0,0.002431,NaN,NaN,NaN,NaN,1314.902329,1314.293647,NaN,0.000463,NaN,NaN,NaN,NaN,0.608683,0.153645,0.455037,44.0,0.007289,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN
3,2018-01-05,1320.300049,9.22,997.719971,17429.500000,0.017125,0.128076,NaN,NaN,NaN,923.052434,904.422974,NaN,0.020598,NaN,NaN,NaN,NaN,18.629460,6.527923,12.101537,1.827917e+10,0.117333,0.163355,NaN,NaN,NaN,15463.067290,15219.615285,NaN,0.015996,NaN,NaN,NaN,NaN,243.452005,60.959085,182.492920,6.249600e+10,0.000000,-0.056295,NaN,NaN,NaN,9.545494,9.652163,NaN,-0.011051,NaN,NaN,NaN,NaN,-0.106668,-0.040794,-0.065874,0.0,0.000682,0.005024,NaN,NaN,NaN,1315.732748,1314.738565,NaN,0.000756,NaN,NaN,NaN,NaN,0.994182,0.321753,0.672430,45.0,0.100208,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.47,NaN,NaN,NaN
4,2018-01-08,1318.599976,9.52,1148.530029,15170.099609,0.151155,0.193005,NaN,NaN,NaN,957.741295,922.504978,NaN,0.038196,NaN,NaN,NaN,NaN,35.236317,12.269602,22.966715,2.673014e+10,-0.129631,-0.002033,NaN,NaN,NaN,15417.995339,15215.947457,NaN,0.013279,NaN,NaN,NaN,NaN,202.047882,89.176844,112.871038,4.408210e+10,0.032538,0.040437,NaN,NaN,NaN,9.541572,9.642373,NaN,-0.010454,NaN,NaN,NaN,NaN,-0.100801,-0.052795,-0.048005,0.0,-0.001288,0.001823,NaN,NaN,NaN,1316.173860,1315.024596,NaN,0.000874,NaN,NaN,NaN,NaN,1.149264,0.487255,0.662009,4.0,-0.280786,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.49,NaN,NaN,NaN

In [59]:
# Quick date coverage check
print("Prices date range:", prices["date"].min().date(), "->", prices["date"].max().date())
print("Trends date range:", trends["date"].min().date(), "->", trends["date"].max().date())

common_start = max(prices["date"].min(), trends["date"].min())
common_end = min(prices["date"].max(), trends["date"].max())
print("Common overlap:", common_start.date(), "->", common_end.date())

Prices date range: 2018-01-02 -> 2026-04-16
Trends date range: 2018-01-01 -> 2026-04-14
Common overlap: 2018-01-02 -> 2026-04-14

In [60]:
# Merge on date (inner join keeps only dates present in both)
df_merged = prices.merge(trends, on="date", how="inner")
df_merged = df_merged.sort_values("date").reset_index(drop=True)

for col in df_merged.columns:
    if col != "date":
        df_merged[col] = pd.to_numeric(df_merged[col], errors="coerce")


def safe_series(df: pd.DataFrame, name: str) -> pd.Series:
    if name in df.columns:
        return pd.to_numeric(df[name], errors="coerce").fillna(0.0)
    return pd.Series(0.0, index=df.index, dtype=float)


def add_engineered_features(df: pd.DataFrame) -> pd.DataFrame:
    """Composite features for tree/linear models (no future leakage — uses same row or lags)."""
    out = df.copy()
    eth = safe_series(out, "ETH")
    btc = safe_series(out, "BTC")

    out["eth_ret_14d"] = eth.pct_change(14)
    out["btc_ret_14d"] = btc.pct_change(14)

    trend_keywords = [
        "bitcoin", "cryptocurrency", "ethereum", "crypto", "btc", "eth",
        "crypto crash", "bitcoin crash", "buy bitcoin", "sell bitcoin",
        "crypto bull run", "solana", "altcoin", "bitcoin price", "crypto wallet",
    ]
    for kw in trend_keywords:
        if kw not in out.columns:
            continue
        s = pd.to_numeric(out[kw], errors="coerce")
        out[f"{kw}_d1"] = s.diff(1)
        rm = s.rolling(7).mean()
        rs = s.rolling(7).std()
        out[f"{kw}_z7"] = (s - rm) / (rs + 1e-9)

    out["sentiment_balance"] = safe_series(out, "eth_news_pos_ratio") - 0.5
    out["news_intensity"] = np.log1p(safe_series(out, "eth_news_count").clip(lower=0))
    out["macro_stress"] = (
        safe_series(out, "treasury_10y_change_7d")
        + safe_series(out, "fed_rate_change_7d")
        + safe_series(out, "cpi_yoy_pct") / 100.0
    )
    out["trend_strength"] = (
        safe_series(out, "eth_macd_hist").abs()
        + safe_series(out, "btc_macd_hist").abs()
        + safe_series(out, "eth_bb_z_20").abs()
    )
    out["risk_regime"] = safe_series(out, "eth_vol_14d") + safe_series(out, "vix_vol_14d")
    out["vol_spread"] = safe_series(out, "eth_vol_14d") - safe_series(out, "btc_vol_14d")
    out["rsi_extreme"] = (safe_series(out, "eth_rsi_14") - 50.0).abs() / 50.0
    out["momentum_gap_7"] = safe_series(out, "eth_ret_7d") - safe_series(out, "btc_ret_7d")
    out["momentum_gap_14"] = out["eth_ret_14d"] - out["btc_ret_14d"]
    out["trend_alignment"] = np.sign(safe_series(out, "eth_ret_7d")) * np.sign(
        safe_series(out, "btc_ret_7d")
    )

    obv_eth = safe_series(out, "eth_obv")
    obv_btc = safe_series(out, "btc_obv")
    for prefix, series in [("eth", obv_eth), ("btc", obv_btc)]:
        ma = series.rolling(20).mean()
        sd = series.rolling(20).std()
        out[f"{prefix}_obv_z20"] = (series - ma) / (sd + 1e-9)

    out["obv_spread"] = safe_series(out, "eth_obv_z20") - safe_series(out, "btc_obv_z20")

    # Extra signals for direction models (same-day + lags only; no future leakage)
    er1 = safe_series(out, "eth_ret_1d")
    br1 = safe_series(out, "btc_ret_1d")
    out["eth_btc_price_ratio"] = eth / (btc + 1e-9)
    out["eth_btc_ratio_ret_1d"] = out["eth_btc_price_ratio"].pct_change(1)
    rm7e, rs7e = er1.rolling(7).mean(), er1.rolling(7).std()
    out["eth_ret_1d_z7"] = (er1 - rm7e) / (rs7e + 1e-9)
    rm7b, rs7b = br1.rolling(7).mean(), br1.rolling(7).std()
    out["btc_ret_1d_z7"] = (br1 - rm7b) / (rs7b + 1e-9)
    ev7 = safe_series(out, "eth_vol_7d")
    out["eth_vol_7d_z7"] = (ev7 - ev7.rolling(7).mean()) / (ev7.rolling(7).std() + 1e-9)
    vx1 = safe_series(out, "vix_ret_1d")
    out["vix_ret_1d_z7"] = (vx1 - vx1.rolling(7).mean()) / (vx1.rolling(7).std() + 1e-9)
    bes = safe_series(out, "btc_eth_spread_1d")
    out["btc_eth_spread_1d_z7"] = (bes - bes.rolling(7).mean()) / (bes.rolling(7).std() + 1e-9)
    st = safe_series(out, "sentiment_balance")
    mg = safe_series(out, "momentum_gap_7")
    for lag in (1, 2, 3):
        out[f"eth_ret_1d_lag{lag}"] = er1.shift(lag)
        out[f"btc_ret_1d_lag{lag}"] = br1.shift(lag)
        out[f"sentiment_balance_lag{lag}"] = st.shift(lag)
        out[f"momentum_gap_7_lag{lag}"] = mg.shift(lag)
    if "date" in out.columns:
        dow = pd.to_datetime(out["date"]).dt.dayofweek.astype(float)
        out["dow_sin"] = np.sin(2 * np.pi * dow / 7.0)
        out["dow_cos"] = np.cos(2 * np.pi * dow / 7.0)
    out["eth_btc_ret_corr_30"] = er1.rolling(30, min_periods=10).corr(br1)
    out["vix_x_eth_vol"] = safe_series(out, "VIX") * safe_series(out, "eth_vol_14d")

    if "buy bitcoin_z7" in out.columns:
        out["buy_signal_pressure"] = out["buy bitcoin_z7"]
    if "altcoin_z7" in out.columns:
        out["altcoin_pressure"] = out["altcoin_z7"]

    return out


df_ml = add_engineered_features(df_merged)

print("Merged (before features) shape:", df_merged.shape)
print("Final ML table shape:", df_ml.shape)
print("Missing values total:", int(df_ml.isna().sum().sum()))
print("Column count:", len(df_ml.columns))
df_ml.head()

Merged (before features) shape: (2081, 101)
Final ML table shape: (2081, 171)
Missing values total: 1163
Column count: 171

,date,GC=F,VIX,ETH,BTC,eth_ret_1d,eth_ret_3d,eth_ret_7d,eth_sma_10,eth_sma_30,eth_ema_12,eth_ema_26,eth_sma_ratio_10,eth_ema_ratio_12_26,eth_vol_7d,eth_vol_14d,eth_bb_z_20,eth_rsi_14,eth_macd,eth_macd_signal,eth_macd_hist,eth_obv,btc_ret_1d,btc_ret_3d,btc_ret_7d,btc_sma_10,btc_sma_30,btc_ema_12,btc_ema_26,btc_sma_ratio_10,btc_ema_ratio_12_26,btc_vol_7d,btc_vol_14d,btc_bb_z_20,btc_rsi_14,btc_macd,btc_macd_signal,btc_macd_hist,btc_obv,vix_ret_1d,vix_ret_3d,vix_ret_7d,vix_sma_10,vix_sma_30,vix_ema_12,vix_ema_26,vix_sma_ratio_10,vix_ema_ratio_12_26,vix_vol_7d,vix_vol_14d,vix_bb_z_20,vix_rsi_14,vix_macd,vix_macd_signal,vix_macd_hist,vix_obv,gc=f_ret_1d,gc=f_ret_3d,gc=f_ret_7d,gc=f_sma_10,gc=f_sma_30,gc=f_ema_12,gc=f_ema_26,gc=f_sma_ratio_10,gc=f_ema_ratio_12_26,gc=f_vol_7d,gc=f_vol_14d,gc=f_bb_z_20,gc=f_rsi_14,gc=f_macd,gc=f_macd_signal,gc=f_macd_hist,gc=f_obv,btc_eth_spread_1d,eth_news_sent_mean,eth_news_sent_wmean,eth_news_sent_std,eth_news_count,eth_news_pos_ratio,eth_news_neg_ratio,federal_funds_rate,cpi,treasury_10y,fed_rate_change_7d,treasury_10y_change_7d,cpi_yoy_pct,bitcoin,cryptocurrency,ethereum,crypto,btc,eth,crypto crash,bitcoin crash,buy bitcoin,sell bitcoin,crypto bull run,solana,altcoin,bitcoin price,crypto wallet,eth_ret_14d,btc_ret_14d,bitcoin_d1,bitcoin_z7,cryptocurrency_d1,cryptocurrency_z7,ethereum_d1,ethereum_z7,crypto_d1,crypto_z7,btc_d1,btc_z7,eth_d1,eth_z7,crypto crash_d1,crypto crash_z7,bitcoin crash_d1,bitcoin crash_z7,buy bitcoin_d1,buy bitcoin_z7,sell bitcoin_d1,sell bitcoin_z7,crypto bull run_d1,crypto bull run_z7,solana_d1,solana_z7,altcoin_d1,altcoin_z7,bitcoin price_d1,bitcoin price_z7,crypto wallet_d1,crypto wallet_z7,sentiment_balance,news_intensity,macro_stress,trend_strength,risk_regime,vol_spread,rsi_extreme,momentum_gap_7,momentum_gap_14,trend_alignment,eth_obv_z20,btc_obv_z20,obv_spread,eth_btc_price_ratio,eth_btc_ratio_ret_1d,eth_ret_1d_z7,btc_ret_1d_z7,eth_vol_7d_z7,vix_ret_1d_z7,btc_eth_spread_1d_z7,eth_ret_1d_lag1,btc_ret_1d_lag1,sentiment_balance_lag1,momentum_gap_7_lag1,eth_ret_1d_lag2,btc_ret_1d_lag2,sentiment_balance_lag2,momentum_gap_7_lag2,eth_ret_1d_lag3,btc_ret_1d_lag3,sentiment_balance_lag3,momentum_gap_7_lag3,dow_sin,dow_cos,eth_btc_ret_corr_30,vix_x_eth_vol,buy_signal_pressure,altcoin_pressure
0,2018-01-02,1313.699951,9.77,884.443970,14982.099609,NaN,NaN,NaN,NaN,NaN,884.443970,884.443970,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,14982.099609,14982.099609,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,9.770000,9.770000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,1313.699951,1313.699951,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN,53,10,8,8,12,69,0,3,42,6,0,1,2,48,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,0.000000,0.0,0.000000,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,0.059033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.781831,0.623490,NaN,0.0,NaN,NaN
1,2018-01-03,1316.199951,9.15,962.719971,15201.000000,0.088503,NaN,NaN,NaN,NaN,896.486431,890.242192,NaN,0.007014,NaN,NaN,NaN,NaN,6.244239,1.248848,4.995392,5.093160e+09,0.014611,NaN,NaN,NaN,NaN,15015.776593,14998.314453,NaN,0.001164,NaN,NaN,NaN,NaN,17.462139,3.492428,13.969712,1.687190e+10,-0.063460,NaN,NaN,NaN,NaN,9.674616,9.724074,NaN,-0.005086,NaN,NaN,NaN,NaN,-0.049459,-0.009892,-0.039567,0.0,0.001903,NaN,NaN,NaN,NaN,1314.084567,1313.885136,NaN,0.000152,NaN,NaN,NaN,NaN,0.199430,0.039886,0.159544,42.0,-0.073892,0.03173,0.03173,0.0,1.0,0.0,0.0,1.42,247.867,2.44,NaN,NaN,NaN,53,12,8,10,12,73,1,3,51,7,0,1,3,46,1,NaN,NaN,0.0,NaN,2.0,NaN,0.0,NaN,2.0,NaN,0.0,NaN,4.0,NaN,1.0,NaN,0.0,NaN,9.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,-2.0,NaN,0.0,NaN,-0.5,0.693147,0.0,18.965103,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,0.063333,0.072828,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974928,-0.222521,NaN,0.0,NaN,NaN
2,2018-01-04,1319.400024,9.22,980.921997,15599.200195,0.018907,NaN,NaN,NaN,NaN,909.476518,896.959215,NaN,0.013955,NaN,NaN,NaN,NaN,12.517304,3.502539,9.014765,1.159602e+10,0.026196,NaN,NaN,NaN,NaN,15105.534070,15042.824508,NaN,0.004169,NaN,NaN,NaN,NaN,62.709562,15.335855,47.373707,3.865510e+10,0.007650,NaN,NaN,NaN,NaN,9.604675,9.686736,NaN,-0.008471,NaN,NaN,NaN,NaN,-0.082061,-0.024326,-0.057735,0.0,0.002431,NaN,NaN,NaN,NaN,1314.902329,1314.293647,NaN,0.000463,NaN,NaN,NaN,NaN,0.608683,0.153645,0.455037,44.0,0.007289,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN,52,14,9,11,13,92,1,3,55,6,0,1,3,41,2,NaN,NaN,-1.0,NaN,2.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,19.0,NaN,0.0,NaN,0.0,NaN,4.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,-5.0,NaN,1.0,NaN,-0.5,0.000000,0.0,56.388472,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,0.062883,-0.007103,NaN,NaN,NaN,NaN,NaN,0.088503,0.014611,-0.5,0.0,0.000000,0.000000,-0.5,0.0,NaN,NaN,NaN,NaN,0.433884,-0.900969,NaN,0.0,NaN,NaN
3,2018-01-05,1320.300049,9.22,997.719971,17429.500000,0.017125,0.128076,NaN,NaN,NaN,923.052434,904.422974,NaN,0.020598,NaN,NaN,NaN,NaN,18.629460,6.527923,12.101537,1.827917e+10,0.117333,0.163355,NaN,NaN,NaN,15463.067290,15219.615285,NaN,0.015996,NaN,NaN,NaN,NaN,243.452005,60.959085,182.492920,6.249600e+10,0.000000,-0.056295,NaN,NaN,NaN,9.545494,9.652163,NaN,-0.011051,NaN,NaN,NaN,NaN,-0.106668,-0.040794,-0.065874,0.0,0.000682,0.005024,NaN,NaN,NaN,1315.732748,1314.738565,NaN,0.000756,NaN,NaN,NaN,NaN,0.994182,0.321753,0.672430,45.0,0.100208,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.47,NaN,NaN,NaN,48,13,8,11,13,82,1,3,51,7,0,1,4,40,2,NaN,NaN,-4.0,NaN,-1.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,-10.0,NaN,0.0,NaN,0.0,NaN,-4.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,-1.0,NaN,0.0,NaN,-0.5,0.000000,0.0,194.594457,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,0.057243,-0.089685,NaN,NaN,NaN,NaN,NaN,0.018907,0.026196,-0.5,0.0,0.088503,0.014611,-0.5,0.0,0.000000,0.000000,-0.5,0.0,-0.433884,-0.900969,NaN,0.0,NaN,NaN
4,2018-01-08,1318.599976,9.52,1148.530029,15170.099609,0.151155,0.193005,NaN,NaN,NaN,957.741295,922.504978,NaN,0.038196,NaN,NaN,NaN,NaN,35.236317,12.269602,22.966715,2.673014e+10,-0.129631,-0.002033,NaN,NaN,NaN,15417.995339,15215.947457,NaN,0.013279,NaN,NaN,NaN,NaN,202.047882,89.176844,112.871038,4.408210e+10,0.032538,0.040437,NaN,NaN,NaN,9.541572,9.642373,NaN,-0.010454,NaN,NaN,NaN,NaN,-0.100801,-0.052795,-0.048005,0.0,-0.001288,0.001823,NaN,NaN,NaN,1316.173860,1315.024596,NaN,0.000874,NaN,NaN,NaN,NaN,1.149264,0.487255,0.662009,4.0,-0.280786,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.49,NaN,NaN,NaN,51,12,11,10,12,89,2,3,42,6,0,1,3,41,1,NaN,NaN,3.0,NaN,-1.0,NaN,3.0,NaN,-1.0,NaN,-1.0,NaN,7.0,NaN,1.0,NaN,0.0,NaN,-9.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,-1.0,NaN,1.0,NaN,-1.0,NaN,-0.5,0.000000,0.0,135.837752,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0,0.075710,0.322605,NaN,NaN,NaN,NaN,NaN,0.017125,0.117333,-0.5,0.0,0.018907,0.026196,-0.5,0.0,0.088503,0.014611,-0.5,0.0,0.000000,1.000000,NaN,0.0,NaN,NaN

In [61]:
# Final validation
print("Date range:", df_ml["date"].min().date(), "->", df_ml["date"].max().date())
print("Duplicate dates:", int(df_ml["date"].duplicated().sum()))
print("Rows:", len(df_ml))
print("Columns:", len(df_ml.columns))

df_ml.tail()

Date range: 2018-01-02 -> 2026-04-14
Duplicate dates: 0
Rows: 2081
Columns: 171

,date,GC=F,VIX,ETH,BTC,eth_ret_1d,eth_ret_3d,eth_ret_7d,eth_sma_10,eth_sma_30,eth_ema_12,eth_ema_26,eth_sma_ratio_10,eth_ema_ratio_12_26,eth_vol_7d,eth_vol_14d,eth_bb_z_20,eth_rsi_14,eth_macd,eth_macd_signal,eth_macd_hist,eth_obv,btc_ret_1d,btc_ret_3d,btc_ret_7d,btc_sma_10,btc_sma_30,btc_ema_12,btc_ema_26,btc_sma_ratio_10,btc_ema_ratio_12_26,btc_vol_7d,btc_vol_14d,btc_bb_z_20,btc_rsi_14,btc_macd,btc_macd_signal,btc_macd_hist,btc_obv,vix_ret_1d,vix_ret_3d,vix_ret_7d,vix_sma_10,vix_sma_30,vix_ema_12,vix_ema_26,vix_sma_ratio_10,vix_ema_ratio_12_26,vix_vol_7d,vix_vol_14d,vix_bb_z_20,vix_rsi_14,vix_macd,vix_macd_signal,vix_macd_hist,vix_obv,gc=f_ret_1d,gc=f_ret_3d,gc=f_ret_7d,gc=f_sma_10,gc=f_sma_30,gc=f_ema_12,gc=f_ema_26,gc=f_sma_ratio_10,gc=f_ema_ratio_12_26,gc=f_vol_7d,gc=f_vol_14d,gc=f_bb_z_20,gc=f_rsi_14,gc=f_macd,gc=f_macd_signal,gc=f_macd_hist,gc=f_obv,btc_eth_spread_1d,eth_news_sent_mean,eth_news_sent_wmean,eth_news_sent_std,eth_news_count,eth_news_pos_ratio,eth_news_neg_ratio,federal_funds_rate,cpi,treasury_10y,fed_rate_change_7d,treasury_10y_change_7d,cpi_yoy_pct,bitcoin,cryptocurrency,ethereum,crypto,btc,eth,crypto crash,bitcoin crash,buy bitcoin,sell bitcoin,crypto bull run,solana,altcoin,bitcoin price,crypto wallet,eth_ret_14d,btc_ret_14d,bitcoin_d1,bitcoin_z7,cryptocurrency_d1,cryptocurrency_z7,ethereum_d1,ethereum_z7,crypto_d1,crypto_z7,btc_d1,btc_z7,eth_d1,eth_z7,crypto crash_d1,crypto crash_z7,bitcoin crash_d1,bitcoin crash_z7,buy bitcoin_d1,buy bitcoin_z7,sell bitcoin_d1,sell bitcoin_z7,crypto bull run_d1,crypto bull run_z7,solana_d1,solana_z7,altcoin_d1,altcoin_z7,bitcoin price_d1,bitcoin price_z7,crypto wallet_d1,crypto wallet_z7,sentiment_balance,news_intensity,macro_stress,trend_strength,risk_regime,vol_spread,rsi_extreme,momentum_gap_7,momentum_gap_14,trend_alignment,eth_obv_z20,btc_obv_z20,obv_spread,eth_btc_price_ratio,eth_btc_ratio_ret_1d,eth_ret_1d_z7,btc_ret_1d_z7,eth_vol_7d_z7,vix_ret_1d_z7,btc_eth_spread_1d_z7,eth_ret_1d_lag1,btc_ret_1d_lag1,sentiment_balance_lag1,momentum_gap_7_lag1,eth_ret_1d_lag2,btc_ret_1d_lag2,sentiment_balance_lag2,momentum_gap_7_lag2,eth_ret_1d_lag3,btc_ret_1d_lag3,sentiment_balance_lag3,momentum_gap_7_lag3,dow_sin,dow_cos,eth_btc_ret_corr_30,vix_x_eth_vol,buy_signal_pressure,altcoin_pressure
2076,2026-04-08,4749.500000,21.040001,2190.335449,71123.359375,-0.022960,0.064897,0.099968,2108.258813,2099.789148,2131.895933,2136.921564,0.038931,-0.002352,0.035040,0.032045,0.567288,49.098139,-5.025630,-21.877817,16.852186,7.770804e+11,-0.011361,0.063311,0.072130,68825.565625,69673.406510,69519.742298,70080.041560,0.033386,-0.007995,0.022883,0.023215,0.465726,49.652877,-560.299262,-910.716172,350.416910,6.252164e+11,-0.183863,-0.118559,-0.322383,25.908,24.631667,25.012469,24.532641,-0.187896,0.019559,0.094306,0.093505,-1.879550,42.314993,0.479828,1.218178,-0.738350,0.0,0.019841,0.021068,0.057324,4608.900000,4865.069987,4671.829274,4751.479761,0.030506,-0.016763,0.019652,0.029032,0.143533,45.167956,-79.650486,-99.389279,19.738793,1519690.0,0.011598,0.0,0.0,0.0,0.0,0.0,0.0,3.64,330.213,4.29,0.0,-0.15,0.04609,22,1,3,9,9,36,0,0,7,1,0,5,0,18,1,-0.006052,-0.001715,2.0,-0.129010,0.0,-0.585540,1.0,0.000000,0.0,-0.561769,1.0,0.944911,5.0,0.112169,-1.0,-1.463850,-1.0,-1.069045,0.0,-0.517549,0.0,-0.377964,0.0,0.0,0.0,-0.705476,0.0,0.0,4.0,0.129500,0.0,0.0,-0.5,0.0,-0.149539,367.836384,0.125550,0.008830,0.018037,0.027838,-0.004336,1.0,1.204356,-0.122128,1.326483,0.030796,-0.011732,-1.061245,-0.943165,0.577716,-1.420396,0.961550,0.063596,0.044741,-0.5,0.042701,0.024751,0.029471,-0.5,0.006563,-0.038286,-0.017480,-0.5,0.005610,0.974928,-0.222521,0.950356,0.674230,-0.517549,0.0
2077,2026-04-09,4792.200195,19.490000,2189.144043,71767.828125,-0.000544,0.038611,0.081852,2110.371069,2104.273018,2140.703335,2140.789896,0.037327,-0.000040,0.035452,0.030861,0.488448,53.835028,-0.086561,-17.519565,17.433005,7.598618e+11,0.009061,0.042231,0.076117,68871.360156,69800.329948,69865.601656,70205.062787,0.042056,-0.004835,0.022793,0.022661,0.711082,55.483017,-339.461131,-796.465164,457.004032,6.640160e+11,-0.073669,-0.193628,-0.363280,25.324,24.683667,24.162858,24.159112,-0.230374,0.000155,0.093223,0.094783,-2.115251,41.496094,0.003746,0.975292,-0.971545,0.0,0.008990,0.029076,0.058816,4633.140039,4851.263330,4690.347877,4754.496089,0.034331,-0.013492,0.019653,0.023919,0.434411,57.937490,-64.148212,-92.341066,28.192854,1520967.0,0.009605,0.0,0.0,0.0,0.0,0.0,0.0,3.64,330.213,4.29,0.0,-0.06,0.04609,20,1,2,10,7,31,1,1,8,1,0,5,0,15,1,0.024197,0.026534,-2.0,-0.408248,0.0,-0.377964,-1.0,-0.944911,1.0,0.073193,-2.0,-1.224745,-5.0,-0.653023,1.0,0.585540,1.0,0.801784,1.0,0.336817,0.0,-0.377964,0.0,0.0,0.0,-0.544705,0.0,0.0,-3.0,-0.602658,0.0,0.0,-0.5,0.0,-0.059539,474.925485,0.125644,0.008200,0.076701,0.005735,-0.002336,1.0,0.680494,0.797291,-0.116797,0.030503,-0.009519,-0.349191,-0.074302,0.531129,-0.163670,0.642765,-0.022960,-0.011361,-0.5,0.027838,0.063596,0.044741,-0.5,0.042701,0.024751,0.029471,-0.5,0.006563,0.433884,-0.900969,0.941887,0.601486,0.336817,0.0
2078,2026-04-10,4761.899902,19.230000,2245.148682,72979.046875,0.025583,0.001491,0.066727,2128.928101,2111.551554,2156.771850,2148.520176,0.054591,0.003841,0.033911,0.031493,1.003398,56.838982,8.251674,-12.365318,20.616991,7.769937e+11,0.016877,0.014433,0.069552,69290.102344,69984.505729,70344.593228,70410.543090,0.053239,-0.000937,0.022346,0.022947,1.150563,57.011389,-65.949862,-650.362103,584.412241,7.017386e+11,-0.013340,-0.254073,-0.238416,24.503,24.703667,23.403957,23.793992,-0.215198,-0.016392,0.078335,0.087868,-1.875942,34.535025,-0.390036,0.702226,-1.092262,0.0,-0.006323,0.022503,0.024593,4671.780029,4837.443327,4701.355881,4755.044520,0.019290,-0.011291,0.018409,0.023911,0.419647,57.937490,-53.688638,-84.610580,30.921942,1520155.0,-0.008706,0.0,0.0,0.0,0.0,0.0,0.0,3.64,330.213,4.31,0.0,0.01,0.04609,19,1,2,9,8,31,1,1,7,1,0,5,0,14,1,0.045959,0.034832,-1.0,-0.866025,0.0,0.000000,0.0,-0.801784,-1.0,-0.207020,1.0,0.207020,0.0,-0.644658,0.0,0.585540,0.0,0.801784,-1.0,-0.207020,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,-1.0,-1.022397,0.0,0.0,-0.5,0.0,0.010461,606.032631,0.119361,0.008546,0.136780,-0.002825,0.011127,1.0,1.083268,1.610189,-0.526921,0.030764,0.008561,0.466655,0.313877,-0.373455,0.280358,-0.566166,-0.000544,0.009061,-0.5,0.005735,-0.022960,-0.011361,-0.5,0.027838,0.063596,0.044741,-0.5,0.042701,-0.433884,-0.900969,0.942205,0.605613,-0.207020,0.0
2079,2026-04-13,4742.399902,19.120001,2370.714844,74484.640625,0.055928,0.082352,0.108465,2166.872388,2126.216654,2189.686157,2164.979040,0.094072,0.011412,0.038219,0.034441,1.993158,62.992076,24.707116,-4.950831,29.657947,8.007029e+11,0.020630,0.047260,0.094098,70104.728906,70271.267187,70981.523597,70712.328093,0.062477,0.003807,0.021947,0.023440,1.597686,59.580235,269.195504,-466.450582,735.646086,7.540168e+11,-0.005720,-0.091255,-0.220864,23.310,24.679000,22.744887,23.447771,-0.179751,-0.029977,0.079131,0.087936,-1.662176,35.286733,-0.702884,0.421204,-1.124088,0.0,-0.004095,-0.001495,-0.008530,4696.820020,4821.173324,4707.670346,4754.107881,0.009704,-0.009768,0.014616,0.021203,0.442677,65.965054,-46.437535,-76.975971,30.538436,1520123.0,-0.035297,0.0,0.0,0.0,0.0,0.0,0.0,3.64,330.213,4.30,0.0,-0.03,0.04609,19,1,2,10,8,33,0,0,7,1,0,5,0,16,1,0.101559,0.050339,0.0,-0.866025,0.0,0.000000,0.0,-0.585540,1.0,0.944911,0.0,0.000000,2.0,0.396942,-1.0,-1.463850,-1.0,-1.069045,0.0,-0.585540,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,2.0,0.408959,0.0,0.0,-0.5,0.0,-0.029539,767.297191,0.122376,0.011000,0.259842,0.014366,0.051220,1.0,1.581962,2.388405,-0.806443,0.031828,0.034584,1.059395,0.341567,1.654110,0.333398,-1.677138,0.025583,0.016877,-0.5,-0.002825,-0.000544,0.009061,-0.5,0.005735,-0.022960,-0.011361,-0.5,0.027838,0.000000,1.000000,0.936359,0.658505,-0.585540,0.0
2080,2026-04-14,4825.000000,18.360001,2323.308594,74181.609375,-0.019997,0.061286,0.129546,2196.851758,2136.084644,2210.243455,2176.707155,0.057563,0.015407,0.034365,0.035200,1.580090,59.469059,33.536299,2.746595,30.789704,7.755177e+11,-0.004068,0.033633,0.109033,70853.745313,70451.459115,71473.844486,70969.311891,0.046968,0.007109,0.019248,0.023397,1.526206,59.882263,504.532594,-272.253947,776.786541,7.004759e+11,-0.039749,-0.057978,-0.230834,22.085,24.576334,22.070289,23.070899,-0.168667,-0.043371,0.079145,0.086928,-1.673176,31.991613,-1.000610,0.136841,-1.137451,0.0,0.017417,0.006844,0.037300,4726.720020,4805.526660,4725.721062,4759.359149,0.020792,-0.007068,0.010328,0.021336,1.017489,68.715374,-33.638087,-68.308395,34.670307,1520411.0,0.015928,0.0,0.0,0.0,0.0,0.0,0.0,3.64,330.213,4.26,0.0,-0.05,0.04609,21,1,3,9,8,37,0,0,6,1,0,5,0,16,1,0.077749,0.051955,2.0,0.641941,0.0,0.000000,1.0,1.069045,-1.0,-0.801784,0.0,0.000000,4.0,1.589439,0.0,-1.069045,0.0,-1.069045,-1.0,-1.656157,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,0.0,0.306719,0.0,0.0,-0.5,0.0,-0.049539,809.156335,0.122128,0.011803,0.189381,0.020513,0.025794,1.0,0.806249,1.281043,-0.474794,0.031319,-0.015993,-1.107150,-0.993265,-0.886230,-0.074150,1.007753,0.055928,0.020630,-0.5,0.014366,0.025583,0.016877,-0.5,-0.002825,-0.000544,0.009061,-0.5,0.005735,0.781831,0.623490,0.933610,0.646275,-1.656157,0.0

In [62]:
# Save final ML datasets (same table: base filename + *_features for selective / GBDT scripts)
df_ml.to_csv(OUTPUT_PATH, index=False)
df_ml.to_csv(OUTPUT_FEATURES_PATH, index=False)
print(f"Saved: {OUTPUT_PATH}")
print(f"Saved: {OUTPUT_FEATURES_PATH}")

Saved: eth_ml_dataset.csv
Saved: eth_ml_dataset_features.csv

In [63]:
df_ml

,date,GC=F,VIX,ETH,BTC,eth_ret_1d,eth_ret_3d,eth_ret_7d,eth_sma_10,eth_sma_30,eth_ema_12,eth_ema_26,eth_sma_ratio_10,eth_ema_ratio_12_26,eth_vol_7d,eth_vol_14d,eth_bb_z_20,eth_rsi_14,eth_macd,eth_macd_signal,eth_macd_hist,eth_obv,btc_ret_1d,btc_ret_3d,btc_ret_7d,btc_sma_10,btc_sma_30,btc_ema_12,btc_ema_26,btc_sma_ratio_10,btc_ema_ratio_12_26,btc_vol_7d,btc_vol_14d,btc_bb_z_20,btc_rsi_14,btc_macd,btc_macd_signal,btc_macd_hist,btc_obv,vix_ret_1d,vix_ret_3d,vix_ret_7d,vix_sma_10,vix_sma_30,vix_ema_12,vix_ema_26,vix_sma_ratio_10,vix_ema_ratio_12_26,vix_vol_7d,vix_vol_14d,vix_bb_z_20,vix_rsi_14,vix_macd,vix_macd_signal,vix_macd_hist,vix_obv,gc=f_ret_1d,gc=f_ret_3d,gc=f_ret_7d,gc=f_sma_10,gc=f_sma_30,gc=f_ema_12,gc=f_ema_26,gc=f_sma_ratio_10,gc=f_ema_ratio_12_26,gc=f_vol_7d,gc=f_vol_14d,gc=f_bb_z_20,gc=f_rsi_14,gc=f_macd,gc=f_macd_signal,gc=f_macd_hist,gc=f_obv,btc_eth_spread_1d,eth_news_sent_mean,eth_news_sent_wmean,eth_news_sent_std,eth_news_count,eth_news_pos_ratio,eth_news_neg_ratio,federal_funds_rate,cpi,treasury_10y,fed_rate_change_7d,treasury_10y_change_7d,cpi_yoy_pct,bitcoin,cryptocurrency,ethereum,crypto,btc,eth,crypto crash,bitcoin crash,buy bitcoin,sell bitcoin,crypto bull run,solana,altcoin,bitcoin price,crypto wallet,eth_ret_14d,btc_ret_14d,bitcoin_d1,bitcoin_z7,cryptocurrency_d1,cryptocurrency_z7,ethereum_d1,ethereum_z7,crypto_d1,crypto_z7,btc_d1,btc_z7,eth_d1,eth_z7,crypto crash_d1,crypto crash_z7,bitcoin crash_d1,bitcoin crash_z7,buy bitcoin_d1,buy bitcoin_z7,sell bitcoin_d1,sell bitcoin_z7,crypto bull run_d1,crypto bull run_z7,solana_d1,solana_z7,altcoin_d1,altcoin_z7,bitcoin price_d1,bitcoin price_z7,crypto wallet_d1,crypto wallet_z7,sentiment_balance,news_intensity,macro_stress,trend_strength,risk_regime,vol_spread,rsi_extreme,momentum_gap_7,momentum_gap_14,trend_alignment,eth_obv_z20,btc_obv_z20,obv_spread,eth_btc_price_ratio,eth_btc_ratio_ret_1d,eth_ret_1d_z7,btc_ret_1d_z7,eth_vol_7d_z7,vix_ret_1d_z7,btc_eth_spread_1d_z7,eth_ret_1d_lag1,btc_ret_1d_lag1,sentiment_balance_lag1,momentum_gap_7_lag1,eth_ret_1d_lag2,btc_ret_1d_lag2,sentiment_balance_lag2,momentum_gap_7_lag2,eth_ret_1d_lag3,btc_ret_1d_lag3,sentiment_balance_lag3,momentum_gap_7_lag3,dow_sin,dow_cos,eth_btc_ret_corr_30,vix_x_eth_vol,buy_signal_pressure,altcoin_pressure
0,2018-01-02,1313.699951,9.770000,884.443970,14982.099609,NaN,NaN,NaN,NaN,NaN,884.443970,884.443970,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,14982.099609,14982.099609,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,9.770000,9.770000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,1313.699951,1313.699951,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,NaN,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN,53,10,8,8,12,69,0,3,42,6,0,1,2,48,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.059033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.781831,0.623490,NaN,0.000000,NaN,NaN
1,2018-01-03,1316.199951,9.150000,962.719971,15201.000000,0.088503,NaN,NaN,NaN,NaN,896.486431,890.242192,NaN,0.007014,NaN,NaN,NaN,NaN,6.244239,1.248848,4.995392,5.093160e+09,0.014611,NaN,NaN,NaN,NaN,15015.776593,14998.314453,NaN,0.001164,NaN,NaN,NaN,NaN,17.462139,3.492428,13.969712,1.687190e+10,-0.063460,NaN,NaN,NaN,NaN,9.674616,9.724074,NaN,-0.005086,NaN,NaN,NaN,NaN,-0.049459,-0.009892,-0.039567,0.0,0.001903,NaN,NaN,NaN,NaN,1314.084567,1313.885136,NaN,0.000152,NaN,NaN,NaN,NaN,0.199430,0.039886,0.159544,42.0,-0.073892,0.03173,0.03173,0.0,1.0,0.0,0.0,1.42,247.867,2.44,NaN,NaN,NaN,53,12,8,10,12,73,1,3,51,7,0,1,3,46,1,NaN,NaN,0.0,NaN,2.0,NaN,0.0,NaN,2.0,NaN,0.0,NaN,4.0,NaN,1.0,NaN,0.0,NaN,9.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,-2.0,NaN,0.0,NaN,-0.5,0.693147,0.000000,18.965103,0.000000,0.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.063333,0.072828,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.5,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974928,-0.222521,NaN,0.000000,NaN,NaN
2,2018-01-04,1319.400024,9.220000,980.921997,15599.200195,0.018907,NaN,NaN,NaN,NaN,909.476518,896.959215,NaN,0.013955,NaN,NaN,NaN,NaN,12.517304,3.502539,9.014765,1.159602e+10,0.026196,NaN,NaN,NaN,NaN,15105.534070,15042.824508,NaN,0.004169,NaN,NaN,NaN,NaN,62.709562,15.335855,47.373707,3.865510e+10,0.007650,NaN,NaN,NaN,NaN,9.604675,9.686736,NaN,-0.008471,NaN,NaN,NaN,NaN,-0.082061,-0.024326,-0.057735,0.0,0.002431,NaN,NaN,NaN,NaN,1314.902329,1314.293647,NaN,0.000463,NaN,NaN,NaN,NaN,0.608683,0.153645,0.455037,44.0,0.007289,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.46,NaN,NaN,NaN,52,14,9,11,13,92,1,3,55,6,0,1,3,41,2,NaN,NaN,-1.0,NaN,2.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,19.0,NaN,0.0,NaN,0.0,NaN,4.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,-5.0,NaN,1.0,NaN,-0.5,0.000000,0.000000,56.388472,0.000000,0.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.062883,-0.007103,NaN,NaN,NaN,NaN,NaN,0.088503,0.014611,-0.5,0.000000,0.000000,0.000000,-0.5,0.000000,NaN,NaN,NaN,NaN,0.433884,-0.900969,NaN,0.000000,NaN,NaN
3,2018-01-05,1320.300049,9.220000,997.719971,17429.500000,0.017125,0.128076,NaN,NaN,NaN,923.052434,904.422974,NaN,0.020598,NaN,NaN,NaN,NaN,18.629460,6.527923,12.101537,1.827917e+10,0.117333,0.163355,NaN,NaN,NaN,15463.067290,15219.615285,NaN,0.015996,NaN,NaN,NaN,NaN,243.452005,60.959085,182.492920,6.249600e+10,0.000000,-0.056295,NaN,NaN,NaN,9.545494,9.652163,NaN,-0.011051,NaN,NaN,NaN,NaN,-0.106668,-0.040794,-0.065874,0.0,0.000682,0.005024,NaN,NaN,NaN,1315.732748,1314.738565,NaN,0.000756,NaN,NaN,NaN,NaN,0.994182,0.321753,0.672430,45.0,0.100208,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.47,NaN,NaN,NaN,48,13,8,11,13,82,1,3,51,7,0,1,4,40,2,NaN,NaN,-4.0,NaN,-1.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,-10.0,NaN,0.0,NaN,0.0,NaN,-4.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,-1.0,NaN,0.0,NaN,-0.5,0.000000,0.000000,194.594457,0.000000,0.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.057243,-0.089685,NaN,NaN,NaN,NaN,NaN,0.018907,0.026196,-0.5,0.000000,0.088503,0.014611,-0.5,0.000000,0.000000,0.000000,-0.5,0.000000,-0.433884,-0.900969,NaN,0.000000,NaN,NaN
4,2018-01-08,1318.599976,9.520000,1148.530029,15170.099609,0.151155,0.193005,NaN,NaN,NaN,957.741295,922.504978,NaN,0.038196,NaN,NaN,NaN,NaN,35.236317,12.269602,22.966715,2.673014e+10,-0.129631,-0.002033,NaN,NaN,NaN,15417.995339,15215.947457,NaN,0.013279,NaN,NaN,NaN,NaN,202.047882,89.176844,112.871038,4.408210e+10,0.032538,0.040437,NaN,NaN,NaN,9.541572,9.642373,NaN,-0.010454,NaN,NaN,NaN,NaN,-0.100801,-0.052795,-0.048005,0.0,-0.001288,0.001823,NaN,NaN,NaN,1316.173860,1315.024596,NaN,0.000874,NaN,NaN,NaN,NaN,1.149264,0.487255,0.662009,4.0,-0.280786,0.00000,0.00000,0.0,0.0,0.0,0.0,1.42,247.867,2.49,NaN,NaN,NaN,51,12,11,10,12,89,2,3,42,6,0,1,3,41,1,NaN,NaN,3.0,NaN,-1.0,NaN,3.0,NaN,-1.0,NaN,-1.0,NaN,7.0,NaN,1.0,NaN,0.0,NaN,-9.0,NaN,-1.0,NaN,0.0,NaN,0.0,NaN,-1.0,NaN,1.0,NaN,-1.0,NaN,-0.5,0.000000,0.000000,135.837752,0.000000,0.000000,1.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.075710,0.322605,NaN,NaN,NaN,NaN,NaN,0.017125,0.117333,-0.5,0.000000,0.018907,0.026196,-0.5,0.000000,0.088503,0.014611,-0.5,0.000000,0.000000,1.000000,NaN,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2076,2026-04-08,4749.500000,21.040001,2190.335449,71123.359375,-0.022960,0.064897,0.099968,2108.258813,2099.789148,2131.895933,2136.921564,0.038931,-0.002352,0.035040,0.032045,0.567288,49.098139,-5.025630,-21.877817,16.852186,7.770804e+11,-0.011361,0.063311,0.072130,68825.565625,69673.406510,69519.742298,70080.041560,0.033386,-0.007995,0.022883,0.023215,0.465726,49.652877,-560.299262,-910.716172,350.416910,6.252164e+11,-0.183863,-0.118559,-0.322383,25.908,24.631667,25.012469,24.532641,-0.187896,0.019559,0.094306,0.093505,-1.879550,42.314993,0.479828,1.218178,-0.738350,0.0,0.019841,0.021068,0.057324,4608.900000,4865.069987,4671.829274,4751.479761,0.030506,-0.016763,0.019652,0.029032,0.143533,45.167956,-79.650486,-99.389279,19.738793,1519690.0,0.011598,0.00000,0.00000,0.0,0.0,0.0,0.0,3.64,330.213,4.29,0.0,-0.15,0.04609,22,1,3,9,9,36,0,0,7,1,0,5,0,18,1,-0.006052,-0.001715,2.0,-0.129010,0.0,-0.585540,1.0,0.000000,0.0,-0.561769,1.0,0.944911,5.0,0.112169,-1.0,-1.463850,-1.0,-1.069045,0.0,-0.517549,0.0,-0.377964,0.0,0.0,0.0,-0.705476,0.0,0.0,4.0,0.129500,0.0,0.0,-0.5,0.000000,-0.149539,367.836384,0.125550,0.008830,0.018037,0.027838,-0.004336,1.0,1.204356,-0.122128,1.326483,0.030796,-0.011732,-1.061245,-0.943165,0.577716,-1.420396,0.961550,0.063596,0.044741,-0.5,0.042701,0.024751,0.029471,-0.5,0.006563,-0.038286,-0.017480,-0.5,0.005610,0.974928,-0.222521,0.950356,0.674230,-0.517549,0.0
2077,2026-04-09,4792.200195,19.490000,2189.144043,71767.828125,-0.000544,0.038611,0.081852,2110.371069,2104.273018,2140.703335,2140.789896,0.037327,-0.000040,0.035452,0.030861,0.488448,53.835028,-0.086561,-17.519565,17.433005,7.598618e+11,0.009061,0.042231,0.076117,68871.360156,69800.329948,69865.601656,70205.062787,0.042056,-0.004835,0.022793,0.022661,0.711082,55.483017,-339.461131,-796.465164,457.004032,6.640160e+11,-0.073669,-0.193628,-0.363280,25.324,24.683667,24.162858,24.159112,-0.230374,0.000155,0.093223,0.094783,-2.115251,41.496094,0.003746,0.975292,-0.971545,0.0,0.008990,0.029076,0.058816,4633.140039,4851.263330,4690.347877,4754.496089,0.034331,-0.013492,0.019653,0.023919,0.434411,57.937490,-64.148212,-92.341066,28.192854,1520967.0,0.009605,0.00000,0.00000,0.0,0.0,0.0,0.0,3.64,330.213,4.29,0.0,-0.06,0.04609,20,1,2,10,7,31,1,1,8,1,0,5,0,15,1,0.024197,0.026534,-2.0,-0.408248,0.0,-0.377964,-1.0,-0.944911,1.0,0.073193,-2.0,-1.224745,-5.0,-0.653023,1.0,0.585540,1.0,0.801784,1.0,0.336817,0.0,-0.377964,0.0,0.0,0.0,-0.544705,0.0,0.0,-3.0,-0.602658,0.0,0.0,-0.5,0.000000,-0.059539,474.925485,0.125644,0.008200,0.076701,0.005735,-0.002336,1.0,0.680494,0.797291,-0.116797,0.030503,-0.009519,-0.349191,-0.074302,0.531129,-0.163670,0.642765,-0.022960,-0.011361,-0.5,0.027838,0.063596,0.044741,-0.5,0.042701,0.024751,0.029471,-0.5,0.006563,0.433884,-0.900969,0.941887,0.601486,0.336817,0.0
2078,2026-04-10,4761.899902,19.230000,2245.148682,72979.046875,0.025583,0.001491,0.066727,2128.928101,2111.551554,2156.771850,2148.520176,0.054591,0.003841,0.033911,0.031493,1.003398,56.838982,8.251674,-12.365318,20.616991,7.769937e+11,0.016877,0.014433,0.069552,69290.102344,69984.505729,70344.593228,70410.543090,0.053239,-0.000937,0.022346,0.022947,1.150563,57.011389,-65.949862,-650.362103,584.412241,7.017386e+11,-0.013340,-0.254073,-0.238416,24.503,24.703667,23.403957,23.793992,-0.215198,-0.016392,0.078335,0.087868,-1.875942,34.535025,-0.390036,0.702226,-1.092262,0.0,-0.006323,0.022503,0.024593,4671.780029,4837.443327,4701.355881,4755.044520,0.019290,-0.011291,0.018409,0.023911,0.419647,57.937490,-53.688638,-84.610580,30.921942,1520155.0,-0.008706,0.00000,0.00000,0.0,0.0,0.0,0.0,3.64,330.213,4.31,0.0,0.01,0.04609,19,1,2,9,8,31,1,1,7,1,0,5,0,14,1,0.045959,0.034832,-1.0,-0.866025,0.0,0.000000,0.0,-0.801784,-1.0,-0.207020,1.0,0.207020,0.0,-0.644658,0.0,0.585540,0.0,0.801784,-1.0,-0.207020,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,-1.0,-1.022397,0.0,0.0,-0.5,0.000000,0.010461,606.032631,0.119361,0.008546,0.136780,-0.002825,0.011127,1.0,1.083268,1.610189,-0.526921,0.030764,0.008561,0.466655,0.313877,-0.373455,0.280358,-0.566166,-0.000544,0.009061,-0.5,0.005735,-0.022960,-0.011361,-0.5,0.027838,0.063596,0.044741,-0.5,0.042701,-0.433884,-0.900969,0.942205,0.605613,-0.207020,0.0
2079,2026-04-13,4742.399902,19.120001,2370.714844,74484.640625,0.055928,0.082352,0.108465,2166.872388,2126.216654,2189.686157,2164.979040,0.094072,0.011412,0.038219,0.034441,1.993158,62.992076,24.707116,-4.950831,29.657947,8.007029e+11,0.020630,0.047260,0.094098,70104.728906,70271.267187,70981.523597,70712.328093,0.062477,0.003807,0.021947,0.023440,1.597686,59.580235,269.195504,-466.450582,735.646086,7.540168e+11,-0.005720,-0.091255,-0.220864,23.310,24.679000,22.744887,23.447771,-0.179751,-0.029977,0.079131,0.087936,-1.662176,35.286733,-0.702884,0.421204,-1.124088,0.0,-0.004095,-0.001495,-0.008530,4696.820020,4821.173324,4707.670346,4754.107881,0.009704,-0.009768,0.014616,0.021203,0.442677,65.965054,-46.437535,-76.975971,30.538436,1520123.0,-0.035297,0.00000,0.00000,0.0,0.0,0.0,0.0,3.64,330.213,4.30,0.0,-0.03,0.04609,19,1,2,10,8,33,0,0,7,1,0,5,0,16,1,0.101559,0.050339,0.0,-0.866025,0.0,0.000000,0.0,-0.585540,1.0,0.944911,0.0,0.000000,2.0,0.396942,-1.0,-1.463850,-1.0,-1.069045,0.0,-0.585540,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,2.0,0.408959,0.0,0.0,-0.5,0.000000,-0.029539,767.297191,0.122376,0.011000,0.259842,0.014366,0.051220,1.0,1.581962,2.388405,-0.806443,0.031828,0.034584,1.059395,0.341567,1.654110,0.333398,-1.677138,0.025583,0.016877,-0.5,-0.002825,-0.000544,0.009061,-0.5,0.005735,-0.022960,-0.011361,-0.5,0.027838,0.000000,1.000000,0.936359,0.658505,-0.585540,0.0
2080,2026-04-14,4825.000000,18.360001,2323.308594,74181.609375,-0.019997,0.061286,0.129546,2196.851758,2136.084644,2210.243455,2176.707155,0.057563,0.015407,0.034365,0.035200,1.580090,59.469059,33.536299,2.746595,30.789704,7.755177e+11,-0.004068,0.033633,0.109033,70853.745313,70451.459115,71473.844486,70969.311891,0.046968,0.007109,0.019248,0.023397,1.526206,59.882263,504.532594,-272.253947,776.786541,7.004759e+11,-0.039749,-0.057978,-0.230834,22.085,24.576334,22.070289,23.070899,-0.168667,-0.043371,0.079145,0.086928,-1.673176,31.991613,-1.000610,0.136841,-1.137451,0.0,0.017417,0.006844,0.037300,4726.720020,4805.526660,4725.721062,4759.359149,0.020792,-0.007068,0.010328,0.021336,1.017489,68.715374,-33.638087,-68.308395,34.670307,1520411.0,0.015928,0.00000,0.00000,0.0,0.0,0.0,0.0,3.64,330.213,4.26,0.0,-0.05,0.04609,21,1,3,9,8,37,0,0,6,1,0,5,0,16,1,0.077749,0.051955,2.0,0.641941,0.0,0.000000,1.0,1.069045,-1.0,-0.801784,0.0,0.000000,4.0,1.589439,0.0,-1.069045,0.0,-1.069045,-1.0,-1.656157,0.0,0.000000,0.0,0.0,0.0,-0.377964,0.0,0.0,0.0,0.306719,0.0,0.0,-0.5,0.000000,-0.049539,809.156335,0.122128,0.011803,0.189381,0.020513,0.025794,1.0,0.806249,1.281043,-0.474794,0.031319,-0.015993,-1.107150,-0.993265,-0.886230,-0.074150,1.007753,0.055928,0.020630,-0.5,0.014366,0.025583,0.016877,-0.5,-0.002825,-0.000544,0.009061,-0.5,0.005735,0.781831,0.623490,0.933610,0.646275,-1.656157,0.0